version: "3.1"
services:
  php:
    container_name: php7
    build:
      context: ./php
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=$APP_NAME
        - APP_PORT=$APP_PORT
    restart: always
    volumes:
      - ./www:/var/www
    ports:
      - $APP_PORT:$APP_PORT
    links:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=$MYSQL_PORT
      - DB_DATABASE=$MYSQL_DATABASE
      - DB_USERNAME=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_PASSWORD
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - $ADMINER_PORT:8080
    links:
      - mysql
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_USER=$MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - mysqldb:/var/lib/mysql:rw
volumes:
  mysqldb: